name: Test

on: push

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - uses: pnpm/action-setup@v4
      - name: Install dependencies
        run: pnpm install

      - run: pnpm tsc
      - run: pnpm lint
      - run: pnpm test
